language: node_js

node_js:
  - "node"

script:
  - npm run build

deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  organization: Project Park
  space: development
  app_name: project-park-app
  username: $CLOUD_FOUNDRY_USERNAME
  password: $CLOUD_FOUNDRY_PASSWORD